# -*- coding: utf-8 -*-
"""assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lJdSIl1Khj91e5jdXkcpospgz9aUjWJm
"""

print("welcome to pathon world! let's start coding")